GET http://localhost:3006/api/blogs

###
POST http://localhost:3006/api/blogs
Content-Type: application/json

{
  "title": "First Blog",
  "author": "Aghyad Deeb",
  "url": "http://www.google.com",
  "likes": "40"
}

###
POST http://localhost:3006/api/blogs
Content-Type: application/json

{
  "title": "Second Blog",
  "author": "Mayar Deeb",
  "url": "http://www.microsoft.com",
  "likes": "420"
}